apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverse-proxy-for-feeds-users-app
  name: reverse-proxy-for-feeds-users-app-svc
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: reverse-proxy-for-feeds-users-app