apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: reverse-proxy-for-feeds-users-app
  name: reverse-proxy-for-feeds-users-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: reverse-proxy-for-feeds-users-app
    spec:
      containers:
      - image: balaudacity2/reverse-proxy-for-feeds-users-app
        name: reverse-proxy-for-feeds-users-app
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always