apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-feeds-app
  labels:
    app: udagram-feeds-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-feeds-app
  template:
    metadata:
      labels:
        app: udagram-feeds-app
    spec:
      containers:
      - name: udagram-feeds-app
        image: balaudacity2/udagram-feeds-app
        ports:
        - containerPort: 80